[package]
name = "rs_concaveman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
robust-predicates = "0.1.*"
libc = "0.2.*"

[build-dependencies]
cc = "1.0.*"